FROM zhuyingda/webster-base
USER work
RUN mkdir /home/work/test_env
WORKDIR /home/work/test_env
RUN git clone https://github.com/zhuyingda/webster.git
WORKDIR /home/work/test_env/webster
RUN npm install
RUN npx playwright install
RUN npm run test